from github import Github
import os

class GitHubAgent:
    def __init__(self, token=None, repo_name=None):
        token = token or os.getenv("GITHUB_TOKEN")
        repo_name = repo_name or os.getenv("GITHUB_REPO")
        self.repo = Github(token).get_repo(repo_name)

    def create_issue(self, title, body="Generated by ProjectPilot AI", assignee=None):
        issue = self.repo.create_issue(
            title=title,
            body=body,
            assignee=assignee if assignee != "TBD" else None
        )
        return issue.html_url
